{% set name = "pdocs" %}
{% set version = "1.1.1" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/pdocs-{{ version }}.tar.gz
  sha256: f148034970220c9e05d2e04d8eb3fcec3575cf480af0966123ef9d6621b46e4f

build:
  number: 0
  noarch: python
  entry_points:
    - pdocs = pdocs.cli:__hug__.cli
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.6,<4.0
    - poetry
  run:
    - dataclasses >=0.7,<0.8
    - docstring_parser >=0.7.2,<0.8.0
    - hug >=2.6,<3.0
    - mako >=1.1,<2.0
    - markdown >=3.0.0,<4.0.0
    - python >=3.6,<4.0

test:
  imports:
    - pdocs
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://pypi.org/project/pdocs/
  summary: A simple program and library to auto generate API documentation for Python modules.
  license: Unlicense
  license_file: LICENSE

extra:
  recipe-maintainers:
    - maresb
    - hadim
