{% set name = "pdocs" %}
{% set version = "1.2.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/pdocs-{{ version }}.tar.gz
  sha256: 996ad4d5039b59a9a112d29abfb3995ec4ed8d8415ddce6947c3a5248adb428b

build:
  number: 1
  noarch: python
  entry_points:
    - pdocs = pdocs.cli:__hug__.cli
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python {{ python_min }}
    - pip
    - poetry
  run:
    - python >={{ python_min }}
    - mako >1.2.2
    - markdown >=3.0.0
    - docstring_parser >=0.7.2
    - hug >=2.6

test:
  imports:
    - pdocs
  commands:
    - pip check
    # # This test must be disabled due to a nonzero exit code
    # # <https://github.com/timothycrosley/pdocs/issues/38>
    # - pdocs --help
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://pypi.org/project/pdocs/
  summary: A simple program and library to auto generate API documentation for Python modules.
  license: Unlicense
  license_file: LICENSE

extra:
  recipe-maintainers:
    - maresb
    - hadim
